apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: cadmusgo/geektime_cloudnative_hw_2
          # 1. 优雅启动
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 2
          # 4. 探活
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          # 3. 资源需求和 QoS 保证
          resources:
            limits:
              memory: 512Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 100m